# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.1
  - 1.2
  - nightly
matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true
notifications:
  email: false
after_success:
  - if [[ $TRAVIS_JULIA_VERSION = 1.2 ]] && [[ $TRAVIS_OS_NAME = linux ]]; then
      julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())';
      julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())';
    fi
jobs:
  include:
    - stage: Documentation
      julia: 1.2
      os: linux
      env:
        - GKSwstype=nul
      script:
        - julia --project=docs -e 'using Pkg; Pkg.instantiate()'
        - julia --project=docs --color=yes docs/make.jl
      after_success: skip
