status = [
  "Julia 1 - ubuntu-latest - x86",
  "Julia 1 - ubuntu-latest - x64",
  "Julia 1.% - ubuntu-latest - x86",
  "Julia 1.% - ubuntu-latest - x64",
  "Julia 1 - macOS-latest - x64",
  "Julia 1.% - macOS-latest - x64",
  "Julia 1 - windows-latest - x86",
  "Julia 1 - windows-latest - x64",
  "Julia 1.% - windows-latest - x86",
  "Julia 1.% - windows-latest - x64",
  "Documentation"
]
delete_merged_branches = true
# Squash commits before merging.
use_squash_merge = true
# Uncomment this to use a two hour timeout.
# The default is one hour.
#timeout_sec = 7200
