status = [
  "continuous-integration/travis-ci/push",
  "Julia 1 - windows-latest - x86",
  "Julia 1 - windows-latest - x64",
  "Julia 1.% - windows-latest - x86",
  "Julia 1.% - windows-latest - x64"
]
delete_merged_branches = true
# Uncomment this to use a two hour timeout.
# The default is one hour.
#timeout_sec = 7200
