name: Docs

on:
  push:
    branches:
      # This is where pull requests from "bors r+" are built.
      - staging
      # This is where pull requests from "bors try" are built.
      - trying
      # Build master branch.
      - main
    tags:
      # When a new release is available
      - 'v*'
  pull_request:
    types: [labeled]

jobs:
  docs:
    name: Documentation
    if: github.event.action != 'labeled' || github.event.label.name == 'preview_docs'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'
      - run: |
          julia --project=docs -e '
            using Pkg
            Pkg.instantiate()'
      - run: |
          julia --project=docs -e '
            using Documenter: doctest
            using CalibrationErrors
            doctest(CalibrationErrors)'
      - run: julia --project=docs docs/make.jl
        env:
          DATADEPS_ALWAYS_ACCEPT: true # Bypass the accept download prompt
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JULIA_DEBUG: Documenter # Print `@debug` statements (https://github.com/JuliaDocs/Documenter.jl/issues/955)
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
